#+TITLE:     Shell utilities
#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fniessen" at-sign "pirilampo.org")
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en

#+PROPERTY:  header-args :eval no
#+SETUPFILE: bigblow-pirilampo.setup

#+name: current-time
#+begin_src emacs-lisp :eval yes :results silent :tangle no
(format-time-string "%Y%m%d.%H%M")
#+end_src

* Context

** Description

The shell utilities are core shell functions and scripts which I wrote when
doing my day-to-day tasks.  Over time, this will become a *powerful toolkit*.

#+begin_note
Library of Babel needs the ~#+name~ field to "ingest" a code block.
#+end_note

** See also

For similar collections, see:

- http://icodesnippet.com/
- http://exploitsdownload.com/
- http://code.google.com/
- [[https://bbs.archlinux.org/viewtopic.php?id=56646&p=1][Post your handy self made command line utilities]]

** Coding style

- http://wiki.bash-hackers.org/scripting/style

- https://google-styleguide.googlecode.com/svn/trunk/shell.xml

  ~variable_name~ (preferred, ~variableName~ accepted) \\
  ~function_name~ \\
  ~CONSTANT_NAME~

** Prerequisites

- Clear
- Diff
- Iconv

* Shell functions
  :PROPERTIES:
  :header-args+: :tangle bin/shellutils :shebang #!/bin/bash
  :END:

Only use alphanumeric characters and the underscore for function names.

** Exit with an error

The exit status follows the conventions for programs such as =grep=, =cmp=, and
=diff=: it is 2 (or greater) if an error occurred.

#+begin_src shell
die () {
    printf "$(basename $0): $@\n" > /dev/stderr
    exit 2                              # An error occurred.
}
#+end_src

~Die~ *must be a function* so that the calling script does exit with an error.

** Check for executable files

#+begin_src shell
files_executables_p () {
    for x in $@
    do
        command -v $x > /dev/null || die "$x not found."
    done
}
#+end_src

** Check for Cygwin executable files

We sometimes have to check that the ~PATH~ is set right, so that Cygwin
executables (for example, ~whoami~ and ~hostname~) are found before their Windows
counterpart -- to avoid problems of spurious ~\r~ added to the output.

#+begin_src shell
files_cygwin_executables_p () {
    for x in $@
    do
        [ "$(command -v $x)" = "/usr/bin/$x" ] \
            || die "$x is not a Cygwin executable."
    done
}
#+end_src

** Find the name of the parent process

The following is supposed to work on Linux, but doesn't on Cygwin.

#+begin_src shell
pname () {
    ps -o command= -p $PPID | tail -n 1 | awk '{print $1}' | awk -F/ '{print $NF}'
}
#+end_src

* Shell scripts
  :PROPERTIES:
  :header-args+: :shebang #!/bin/bash
  :END:

** Send an email
   :PROPERTIES:
   :header-args+: :tangle bin/mail :shebang #!/bin/bash
   :END:

Send a mail to one or more people.

*** Name

#+begin_src shell :noweb yes :padline no
# mail -- Send simple mail
#+end_src

*** Synopsis

#+begin_src shell
Usage ()
{
    cat << EOF 1>&2
Usage: $CMD [-s SUBJECT] [-a ATTACHMENT]... [-c CC-ADDR] [-b BCC-ADDR] [-f FROM-ADDR] TO-ADDR
Try '$CMD -h' for more information.
EOF
    exit 2
}
#+end_src

*** Description

Send an email using ~mail~:

#+begin_src shell :tangle no
mail -s "Subject" recipient@example.com < /path/to/file
cat /path/to/file | mail -s "Subject" recipient@example.com
echo "Message" | mail -s "Subject" recipient@example.com
#+end_src

*** Options

The following options shall be supported:

#+begin_src shell :noweb yes
Help ()
{
    cat << EOF
This is $CMD, version: <<current-time()>>.

Usage: $CMD [-s SUBJECT] [-a ATTACHMENT]... [-c CC-ADDR] [-b BCC-ADDR] [-f FROM-ADDR] TO-ADDR
Send simple mail.
Example: $CMD -s 'Disk failure' bill@example.com < /tmp/message

Options:
  -s  Specify subject on command line
  -a  Attach a file
  -c  Send carbon copies to (comma separated) list of recipients
  -b  Send blind carbon copies to (comma separated) list of recipients
  -f  Set the From address
  -h  Display this help and exit
EOF
    exit 0
}
#+end_src

*** Stdin

When ~mail~ is invoked, standard input shall be the message to be delivered to
the specified addresses.

*** Input files

None.

*** Environment variables

The behavior of ~mail~ is affected by the following environment variable:

- ~SMTP~ ::
     The SMTP connection is made to the server specified by the variable ~SMTP~.

*** Stdout

The standard output shall be that of the ~blat~ command.

*** Stderr

The standard error shall be used only for diagnostic messages.

*** Output files

None.

*** Exit status

The ~mail~ utility returns one of the following values upon exit:

- 0 ::
     Successful completion: one mail was sent.

- 2 ::
     Invalid options were specified on the command line or shell input was
     missing.

Otherwise, the exit status of ~mail~ shall be that of the ~blat~ command.

*** Examples

Here's a shell script that reports the disk usage:

#+begin_src shell :tangle no
( printf "Disk usage:\n" ; du -sh ) | mail -s "Disk usage report" recipient@example.com
#+end_src

Here's another one to backup a configuration folder, archive it, and send it as
an attachment:

#+begin_src shell :tangle no
tar -zcf ~/backup.tar.gz ~/files_to_backup
printf "Archived configuration files\n" | mail -s "Backup data" -a ~/backup.tar.gz recipient@example.com
#+end_src

*** Code

#+begin_src shell
# command name
CMD=$(basename $0)

. shellutils || exit 2

if [ $# -eq 0 ]; then
    Usage
fi

# check for Cygwin executable files (and not their Windows counterpart)
files_cygwin_executables_p "whoami" "hostname"

# default values
SUBJECT="none"
ATTFILES=""                             # files to be attached
CC=""
BCC=""
FROM="<$(whoami)@$(echo $(hostname) | tr '[:upper:]' '[:lower:]')>"
: ${SMTP:="smtp"}                       # set var if not already set
BODY="--"                               # stdin.txt

while getopts "s:c:b:f:a:h" opt
do
    case "$opt" in
        s) SUBJECT="$OPTARG";;
        a) ATTFILES="$ATTFILES $OPTARG";;
        c) CC="$OPTARG";;
        b) BCC="$OPTARG";;
        f) FROM="$OPTARG";;
        h) Help;;
        ,*) Usage;;
    esac
done
shift $(($OPTIND - 1))

MAILTO="$1"
if [ "$MAILTO" = "" ]; then
    Usage
fi

# check presence of stdin contents
[ -t 0 ] && die "Message body is missing."

# check for executable files
files_executables_p "blat"

ATT_SWITCH=""
for attach in $ATTFILES
do
    if [ ! -r $attach ]
    then
        die "File $attach does not exist or is not readable."
    else
        # binary vs text file
        if [ "$(file --brief --mime $attach 2> /dev/null | cut -d/ -f 1)" = "text" ]
        then
            ATT_SWITCH="$ATT_SWITCH -attacht $(cygpath -w $attach)"
        else
            ATT_SWITCH="$ATT_SWITCH -attach $(cygpath -w $attach)"
        fi
    fi
done

CC_SWITCH=""
[ "$CC" = "" ] || CC_SWITCH="-cc ${CC}"

BCC_SWITCH=""
[ "$BCC" = "" ] || BCC_SWITCH="-bcc ${BCC}"

blat -to "$MAILTO" \
     $CC_SWITCH \
     $BCC_SWITCH \
     -subject "$SUBJECT" \
     -f "$FROM" \
     -server "$SMTP" \
     $ATT_SWITCH

# mail ends here
#+end_src

** Echo text in color

#+begin_src shell :tangle ~/bin/cecho
cecho () {
    black="\e[30m"
    red="\e[31m"
    green="\e[32m"
    yellow="\e[33m"
    blue="\e[34m"
    magenta="\e[35m"
    cyan="\e[36m"
    white="\e[37m"

    BLACK="\e[1;30m"
    RED="\e[1;31m"
    GREEN="\e[1;32m"
    YELLOW="\e[1;33m"
    BLUE="\e[1;34m"
    MAGENTA="\e[1;35m"
    CYAN="\e[1;36m"
    WHITE="\e[1;37m"

    reset="\e[0m"

    color=${YELLOW}
    printf "$color$1$reset\n"
}

cecho "$@"
#+end_src

* VC
  :PROPERTIES:
  :header-args+: :shebang #!/bin/bash
  :END:

http://superuser.com/questions/44787/looping-through-subdirectories-and-running-a-command-in-each

#+name: vc-update
#+begin_src shell :results verbatim
for dir in ~/src/*
do
    cecho "Updating $dir:"
    if [ -d $dir/.git ]; then
        (cd $dir && git pull)
    elif [ -d $dir/.svn ]; then
        (cd $dir && svn update)
    fi
    printf "\n"
done
#+end_src

If you need it to be recursive:

#+name: git-recursive-update
#+begin_src shell
find -type d -printf "%f" -exec  sh -c "cd \"{}\" && git pull"  \;
#+end_src

See http://snipplr.com/view/6228/recursively-find-subversion-working-copies-and-update/

** Ignore files from the command line

Add a file (or a file glob pattern) to ignore without deleting the previous
value of the ~svn:ignore~ property... from the command line.

#+begin_src shell :tangle bin/svnignore
# Usage: svnignore admin/notes/\*.tex

target="$1"
targetdirectory=$(dirname $target)
targetfilepattern=$(basename $target)

svnignores=$(svn propget svn:ignore "$targetdirectory")
svnignores="$svnignores"$'\n'"$targetfilepattern"
printf "Ignore '$targetfilepattern'\n"
svn propset svn:ignore "$svnignores" "$targetdirectory"
#+end_src

* Web security assessments

** HTTP

From Hacking Exposed Web Applications:

#+begin_src shell :tangle bin/getit.sh
#!/bin/sh
# mike's getit.sh script
if [ -z $1 ]; then
    echo -e "\n\tUsage: $0 <host> <URL>"
    exit
fi
echo -e "GET $2 HTTP/1.0\n\n" | \
nc -vv $1 80
#+end_src

#+begin_src shell
getit.sh www.missioncriticalit.com /index.html
#+end_src

#+begin_src shell
getit.sh www.victim.com /index.html | grep -i "<form"
#+end_src

#+begin_src shell
getit.sh www.victim.com /index.html | grep -i "input type"
#+end_src

** HTTPS

#+begin_src shell :tangle bin/sgetit.sh
#!/bin/sh
# mike's sgetit.sh script
if [ -z $1 ]; then
    echo -e "\n\tUsage: $0 <SSL host> <URL>"
    exit
fi
echo -e "GET $2 HTTP/1.0\n\n" | \
openssl s_client -quiet -connect $1:443 2>/dev/null
#+end_src

#+begin_src shell
sgetit.sh www.victim.com /secure/admin.html
#+end_src

* Netcat

Here is a script which will port scan and banner grab automatically with
netcat. It will check for the SSH and MySQL version by connecting and saving
the results and it will see if the HTTP server is vulnerable to the =TRACE=
method, look in the dumpfile ~/tmp/bannergrab~ and look for
=<script>alert(123)</script>= if you can find that back you got yourself a
vulnerable server.

#+begin_src shell :tangle bin/nc_bgrab
#!/bin/sh

range="10.10.10.";

# You can change this to a port range $(seq 20 25) is port 20-25
ports="20 21 22 23 25 53 80 110 111 443 3306 6000";

http_header="HEAD / HTTP/0.1\n\n";

for host in $(seq 2 254); do
    for port in $ports; do
        echo "[+] Testing "$range$host":"$port;
        result=$(nc -zv -w 1 $range$host $port 2>&1 | grep succeeded);
        if [ -n "$result" ]; then
            echo "\n"$range$host":"$port"\n" >> "/tmp/bannergrab"
            if [ "$port" -eq "22" ]; then
                echo "Found open port "$range$host":"$port" Here might be some SSH server, it echoes the SSH version to you on connecting when lucky.";
                nc -v -w 1 $range$host $port >> "/tmp/bannergrab";
            fi;
            if [ "$port" -eq "80" ]; then
                echo "Found open port "$range$host":"$port" Trying to fingerprint with HEAD and see if the server is vulnerable to TRACE XSSing";
                echo $http_header | nc -v -w 1 $range$host $port >> "/tmp/bannergrab"
                echo "TRACE / HTTP/1.1\nHost: $range$host\nuser-agent: <script>alert(123)</script>\n\n" | nc -v -w 2 $range$host $port >> "/tmp/bannergrab"
            fi;
            if [ "$port" -eq "3306" ]; then
                echo "Found open port "$range$host":"$port" Possible MySQL installation found, saving the banner for later inspection, the MySQL version can be found in this.";
                nc -v -w 1 $range$host $port >> "/tmp/bannergrab";
            fi;
        fi;
    done
done
#+end_src

A lot more on http://h.ackack.net/cheatsheets/netcat/: how to workaround =-e
cmd.exe= option which disappeared, etc.

** Scan only certain ports

#+begin_src shell
nc -z -w 1 -v -v 10.10.10.11 20-30,53,80,100-112,443,6000-6050
#+end_src

** DNS

#+begin_src shell
nc -p 53 -w 2 -v -v firewall.yournetwork.com 53
nc -u -p 53 -w 2 -v -v firewall.yournetwork.com 53
#+end_src

** Spoof source IP address

=-s= option to Netcat: does not work under Cygwin...

** Socat

Learning socat in terms of netcat: http://jdimpson.livejournal.com/6534.html

- *Remote access server*

  #+begin_src shell
  socat TCP-LISTEN:2323,reuseaddr EXEC:/bin/bash
  #+end_src

- *Data forwarder* (aka simple proxy)

  #+begin_src shell
  socat TCP-L:2323 TCP:localhost:22
  #+end_src

  And of course, you can replace either address with any other socat address
  we've already talked about (UDP, UDP-L), or ones we'll talk about in another
  post (e.g. SSL).

** Packet forger

SendIP

** Lauching attacks via Tor

http://www.oreillynet.com/onlamp/blog/2005/07/launching_attacks_via_tor.html
