#!/bin/bash
die () {
    printf "$(basename $0): $@\n" > /dev/stderr
    exit 2                              # an error occurred
}

pname () {
    ps -o command= -p $PPID | tail -n 1 | awk '{print $1}' | awk -F/ '{print $NF}'
}
